server:
  port: 46002

spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql://localhost:45002/project050611yjy_logging?useSSL=false&serverTimezone=UTC
    username: root
    password: local1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址

mybatis:
  mapper-locations: classpath:mapper/*.xml
