# 应用服务 WEB 访问端口
server:
  port: 46000


spring:
  datasource:
    url: jdbc:mysql://localhost:45002/project050611yjy_user?useSSL=false&serverTimezone=UTC
    username: root
    password: local1234
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations:  classpath:mappers/*.xml
  #指定Mybatis的实体目录
#  type-handlers-package: cn.beforedark.userservice


